name: build_keys
description: "Build the `GameShortcutKey class."
version: 1.0.0

environment:
  sdk: ^3.5.0-180.3.beta

dependencies:
  dart_style: ^2.3.6
  dio: ^5.4.3+1
  html: ^0.15.4
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
